config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts, only: [:index, :new, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :likes, only: [:show]

  resources :users, only: [:show]


  resources :posts do
    collection do
      get 'search'
      get 'about'
    end
  end

  resources :categories do
    collection do
      get 'ruby'
      get 'rails'
      get 'aws'
      get 'js'
      get 'docker'
    end
  end

  resources :profiles, only: [:new, :create, :edit, :update]

  get '/blocks', to: 'blocks#index'
  post '/block/transactions', to: 'block/transactions#create'
  post '/blocks', to: 'blocks#create'
  post '/nodes', to: 'nodes#create'
  put '/blocks', to: 'blocks#update_all'


end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @profile = Profile.new
  end

  def create
    Profile.create(profile_params)
    redirect_to user_path(id: current_user.id), notice: 'プロフィールを保存しました'
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
    redirect_to user_path(current_user.id)
  end

  private
  def profile_params
    params.require(:profile).permit(:content, :region, :website).merge(user_id: current_user.id)
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class='form-group'>
  <%= form.text_area :content, placeholder: "text" , rows: "10", class: 'form-control' %>
  </br>
  <%= form.text_field :region, placeholder: "場所", class: 'form-control'%>
  </br>
  <%= form.text_field :website, placeholder: "Url", class: 'form-control'%>
  </br>
  <%= form.submit "SEND", class: 'btn btn-secondary' %>
</div>

app/views/profiles/_profile.html.erb
  <div class="card col-sm-6 col-md-4 mt-4">
    <% if @user.image.blank? %>
      <%= image_tag 'default_user.png', class: "img-fluid" %>
    <% else %>
      <%= image_tag @user.image.url, class: "img-fluid" %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title text-secondary text-center"><%= @user.name %></h5>
      <table class="table">
        <thead>
          <tr>
            <th class="text-center">投稿記事数</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="text-center"><%= @user.posts.length %></td>
          </tr>
        </tbody>
      </table>
      <p class="card-text gray">
        <% if @profile.nil? %>
          よろしくお願いします。
        <% else @profile.content || @profile.region || @profile.website %>
          <p> <%= @profile.content %> </p>
          <p> <i class="fas fa-map-marker-alt"></i> <%= @profile.region %> </p>
          <p>
            <a href="<%= @profile.website %>" target="_blank" rel="noopener">
              <%= @profile.website %>
            </a>
          </p>
        <% end %>
      </p>
      <% if current_user == @user %>
        <% if @profile.blank? %>
          <%= link_to "プロフィールを書く", "/profiles/new/", class: "btn btn-secondary" %>
        <% else %>
          <%= link_to "プロフィールを編集する", edit_profile_path(@profile.id), method: :get, class: "btn btn-secondary" %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/profiles/edit.html.erb
<div class="col-md-6 offset-md-3 px-5 mt-4">
  <div class="jumbotron px-5">
    <%= form_with(model: @profile, local: true, method: :patch, class: "text-center") do |form| %>
      <h3>
        自己紹介
      </h3>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="col-md-6 offset-md-3 px-5 mt-4">
  <div class="jumbotron px-5">
    <h3>
      自己紹介
    </h3>
    </br>
    <%= form_with(model: @profile, local: true, class: "text-center") do |form| %>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>