config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts, only: [:index, :new, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :likes, only: [:show]

  resources :users, only: [:show]


  resources :posts do
    collection do
      get 'search'
      get 'about'
    end
  end

  resources :categories do
    collection do
      get 'ruby'
      get 'rails'
      get 'aws'
      get 'js'
      get 'docker'
    end
  end

  resources :profiles, only: [:new, :create, :edit, :update]

  get '/blocks', to: 'blocks#index'
  post '/block/transactions', to: 'block/transactions#create'
  post '/blocks', to: 'blocks#create'
  post '/nodes', to: 'nodes#create'
  put '/blocks', to: 'blocks#update_all'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,omniauth_providers: [:facebook, :google_oauth2]

  has_many :posts, dependent: :destroy
  has_one :profiles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  validates :name,                presence: true, length: {maximum: 6}

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  mount_uploader :image, ImageUploader

    def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        name:  auth.info.name,
        password: Devise.friendly_token[0, 20],
        image:  auth.info.image
      )
    end

    user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def google_oauth2
    callback_from :google
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC")
    @profile = Profile.find_by(user_id: params[:id])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light  mb-3">
  <div class="mx-auto" style="width: 80%;">
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "投稿一覧", user_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "いいね記事一覧", like_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white mx-auto p-0 my-2" style="width: 80%;">
  <div class="container">
    <a class="navbar-brand " href="/">
      <img src="<%= asset_path "tech_recommend_logo.png" %>" width="30" height="30" class="d-inline-block align-top" alt="ブランド">
        TechRecommend
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "About", about_posts_path, class: "nav-link" %>
        </li>
      </ul>
      <% if user_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "投稿する", new_post_path, class: "nav-link" %>
            </li>
            <div class="dropdown show">
              <li class="nav-item pt-2 mr-2 dropdown-toggle cursor-pointer" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.image.blank? %>
                  <%= image_tag 'default_user.png', size: '30x30' %>
                <% else %>
                  <%= image_tag current_user.image.url, size: '30x30' %>
                <% end %>
                <%= current_user.name %>
              </li>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to "マイページ", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "設定", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "ログアウト", destroy_user_session_path, class: "dropdown-item", method: :delete %>
              </div>
            </div>
          </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/users/_post.html.erb
<% @posts.each do |post| %>
  <a href="<%= post.url %>" target="_blank" rel="noopener">
    <div class="card mt-2 mb-3">
      <div class="row no-gutters">
        <div class="col-md-1 ml-3 mt-3">
          <% if post.img.present? %>
            <%= image_tag post.img, class: "img-fluid" %>
          <% else %>
            <%= image_tag 'noimage.jpg', class: "img-fluid" %>
          <% end %>
        </div>
        <div class="col-md-10 mb-0">
          <div class="card-body">
            <h6 class="card-title"><%= truncate(post.title.to_s, length:40) %></h5>
          </div>
        </div>
      </div>
    </div>
  </a>
<% end %>

app/views/users/show.html.erb
<%= render "mypage_nav" %>
<div class="container mx-auto my-5" style="width: 80%">
  <div class="row">
    <%= render "profiles/profile" %>
    <div class="col-sm-6 col-md-8 col-lg-8 mt-4">
      投稿一覧
      <% if @user.liked_posts.blank? %>
        <div class="gray mt-3">
          まだ投稿した記事がありません
        </div>
      <% else %>
        <%= render "post" %>
      <% end %>
  </div>
  </div>
</div>