config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts, only: [:index, :new, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :likes, only: [:show]

  resources :users, only: [:show]


  resources :posts do
    collection do
      get 'search'
      get 'about'
    end
  end

  resources :categories do
    collection do
      get 'ruby'
      get 'rails'
      get 'aws'
      get 'js'
      get 'docker'
    end
  end

  resources :profiles, only: [:new, :create, :edit, :update]

  get '/blocks', to: 'blocks#index'
  post '/block/transactions', to: 'block/transactions#create'
  post '/blocks', to: 'blocks#create'
  post '/nodes', to: 'nodes#create'
  put '/blocks', to: 'blocks#update_all'


end

app/models/post.rb
class Post < ApplicationRecord

  require 'nokogiri'
  require 'open-uri'

  before_save :scrape

  belongs_to :user
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :url, presence: true
  validates :url, uniqueness: true 
  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/

  def self.search(search)
    return Post.all unless search
    Post.where('title LIKE(?)', "%#{search}%")
  end

  def scrape
    url = self.url
    charset = nil 
    html = open(url) do |f|
      charset = f.charset 
      f.read 
    end
    doc = Nokogiri::HTML.parse(html, charset)
    img = doc.css('//meta[property="og:image"]/@content').to_s
    if img.length > 255
      img = ''
    end
    title = doc.title.to_s
    description = doc.css('//meta[property="og:description"]/@content').to_s
    while description.length > 255 do
      description = description.chop
    end
    self.img = img
    self.title = title
    self.description = description
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :today, only: :index


  def index
    @posts = Post.includes(:user).order("created_at DESC")
    @like = Like.new
    @recommends = session[:today]
  end


  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path, notice: '投稿を追加しました。'
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  def today
    if session[:today].blank?
      session[:today] = Post.order("RAND()").limit(3)
      redirect_to root_path
    end
  end

  def destroy_today
    session[:today] = ''
    puts "成功しました"
  end


  private

  def post_params
    params.require(:post).permit(:url, category_ids: []).merge(user_id: current_user.id)

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <p class="gray pt-5">
    テックエキスパートで勉強する時に役立つ記事を投稿してください。
  </p>
  <%= image_tag 'article_tech.png', class: "img-fluid mx-auto d-block col-sm-6 col-md-6 col-lg-6  pb-3" %>
  <%= f.text_field :url, class: "col-sm-10 col-md-8 col-lg-6", placeholder: "おすすめの記事のURL" %>
  <div class="red">
    <%= @post.errors.full_messages_for(:url).first%>
  </div>
  
  <div class="col-md-6 mx-auto mt-2 mb-2">
    <div class="form-group">
      <label class="label-checkbox" for="post_category_ids_1">
          <input id="post_category_ids_1" name="post[category_ids][]" type="checkbox" value="1">
          <span class="custom-checkbox"></span>ruby
      </label>
      <input name="post[category_ids][]" type="hidden" value=""> 

      <label class="label-checkbox" for="post_category_ids_2">
          <input id="post_category_ids_2" name="post[category_ids][]" type="checkbox" value="2">
          <span class="custom-checkbox"></span>rails
      </label>
      <input name="post[category_ids][]" type="hidden" value=""> 

      <label class="label-checkbox" for="post_category_ids_3">
          <input id="post_category_ids_3" name="post[category_ids][]" type="checkbox" value="3">
          <span class="custom-checkbox"></span>aws
      </label>
      <input name="post[category_ids][]" type="hidden" value=""> 

      <label class="label-checkbox" for="post_category_ids_4">
          <input id="post_category_ids_4" name="post[category_ids][]" type="checkbox" value="4">
          <span class="custom-checkbox"></span>JS
      </label>
      <input name="post[category_ids][]" type="hidden" value=""> 

      <label class="label-checkbox" for="post_category_ids_5">
          <input id="post_category_ids_5" name="post[category_ids][]" type="checkbox" value="5">
          <span class="custom-checkbox"></span>docker
      </label>
      <input name="post[category_ids][]" type="hidden" value=""> 
    </div>
  </div>
  <%= f.submit "投稿する", class: "btn btn-outline-secondary mb-2" %>
  <nav class="navbar navbar-expand-lg navbar-light justify-content-center">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/">TOP</a>
        </li>
      </ul>
  </nav>
<% end %>

app/views/posts/_post.html.erb
<div class="col-sm-6 col-md-4 col-lg-3 mb-3">
  <a href="<%= post.url %>" target="_blank" rel="noopener">
    <div class="zoomIn">
      <% if post.img.present? %>
        <img src="<%= post.img %>" width="200" height="200" class="card-img-top">
      <% else %>
        <%= image_tag 'noimage.jpg', class: "card-img-top", size: '200x200' %>
      <% end %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= truncate(post.title.to_s, length:50)%></h5>
      <p class="card-text"><%= truncate(post.description.to_s, length:50)%></p>
    </div>
  </a>
    <div class="card-text d-flex justify-content-between">
      <a href="/users/<%= post.user.id %>">
        <% if post.user.image.present? %>
          <img src="<%= post.user.image %>" width="20" height="20">
        <% else %>
          <%= image_tag 'default_user.png', size: '20x20' %>
        <% end %>
        <%= post.user.name %>
      </a>
      <div>
        <% if current_user.already_liked?(post) %>
          <%= link_to post_like_path([post.id],id: post.id), method: :delete do %>
            <%= icon("fas", "heart text-success")%>
          <% end %>
        <% else %> 
          <%= link_to post_likes_path(post.id), method: :post do %>
            <%= icon("far", "heart text-success")%>
          <% end %>
        <% end %>
        <%= post.likes.count %>
      </div>
      <% if user_signed_in? && current_user.id == post.user_id %>
        <small>
          <%= link_to post_path(post.id), method: :delete,data:{confirm:"本当に削除しますか？",
        commit:"削除する",cancel:"やめる",title:"ご確認ください" } do %> 
            <%= icon("fas", "trash-alt")%>
          <% end %>
        </small>
      <% end %>
    </div>
</div>

app/views/posts/_posts.html.erb
<div class="card-group mx-auto" style="width: 80%;">

  <%= render 'today_recommend' %>

  <h2 class="d-block col-md-12 mb-3 gray">
    新着一覧
  </h2>

  <%= render @posts %>

</div>

app/views/posts/_search.html.erb
<nav class="navbar navbar-expand-lg navbar-light  mb-3">
  <div class="mx-auto" style="width: 80%;">
    <div class="collapse navbar-collapse float-right" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "ruby", ruby_categories_path, class: "nav-link", id: "ruby" %>
        </li>
        <li class="nav-item">
          <%= link_to "rails", rails_categories_path, class: "nav-link", id: "rails" %>
        </li>
        <li class="nav-item">
          <%= link_to "aws", aws_categories_path, class: "nav-link", id: "aws" %>
        </li>
        <li class="nav-item">
          <%= link_to "JS", js_categories_path, class: "nav-link", id: "js" %>
        </li>
        <li class="nav-item">
           <%= link_to "docker", docker_categories_path, class: "nav-link", id: "docker" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <%= form_with(url: search_posts_path, local: true, method: :get, class: "form-inline my-2 my-lg-0") do |form| %>
          <%= form.text_field :keyword,type: "search", placeholder: "投稿を検索する", class: "form-control mr-sm-2" %>
          <%= form.submit "検索", class: "btn btn-outline-secondary my-2 my-sm-0",type: "submit" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/_today_recommend.erb
<h2 class="d-block col-md-12 mb-3 gray">
    今日のおすすめ記事
</h2>
<div id="carouselExampleControls" class="carousel slide mb-4 ml-3" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="<%= @recommends.first["url"] %>" target="_blank" rel="noopener">
        <img src="<%= @recommends.first["img"] %>"width="40" height="40" alt="First slide">
        <%= @recommends.first["title"] %>
      </a>
    </div>
    <div class="carousel-item">
      <a href="<%= @recommends.second["url"] %>" target="_blank" rel="noopener">
        <img src="<%= @recommends.second["img"] %>"width="40" height="40" alt="First slide">
        <%= @recommends.second["title"] %>
      </a>
    </div>
    <div class="carousel-item">
      <a href="<%= @recommends.third["url"] %>" target="_blank" rel="noopener">
        <img src="<%= @recommends.third["img"] %>"width="40" height="40" alt="First slide">
        <%= @recommends.third["title"] %>
      </a>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/posts/about.html.erb
<div class="container pt-5">
  <div class="jumbotron col-md-6 mx-auto">
    <h2 class="display-6">TechRecommendについて</h1>
    <p class="lead">このサイトはテックエキスパートの受講生がカリキュラムで学習する時に見つけた参考サイトを共有することを目的に作りました。</p>
    <hr class="my-4">
    <p>ここで情報を共有して効率的に学習しましょう。</p>
  </div>
  <nav class="navbar navbar-expand-lg navbar-light justify-content-center">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/">TOP</a>
              </li>
            </ul>
          </div>
        </nav>
</div>

app/views/posts/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/posts">投稿一覧へ戻る</a>
  </div>
</div>

app/views/posts/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'search'%>
<%= render 'posts'%>

app/views/posts/new.html.erb
<%= render 'search'%>


<div class="contents row text-center">
  <div class="container">
    <div class="form-group">
      <%= render "form" %>
    </div>
  </div>
</div>